apiVersion: app/v1
kind: Job
metadata:
  name: falsk-app
spec:
  parallelism: 1    
  completions: 1    
  activeDeadlineSeconds: 1800 
  backoffLimit: 6   
  template:         
    metadata:
      name: falsk-app
    spec:
      containers:
       - name: falsk-app
         image: test-flask-app
         port:
          - containerPort: 8080
            protocol: TCP
      restartPolicy: OnFailure 
